version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/zignaly-affiliates
hooks:
  # BeforeInstall:
  #   - location: scripts/BeforeInstallHook.sh
  #     timeout: 300
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
permissions:
  - object: /var/www/zignaly-affiliates
    owner: affiliates
    group: affiliates
    type:
      - directory
      - file
