name: CI/CD Pipeline
on:
  push:
    branches: [master]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install and build client
        run: |
          cd client
          yarn
          yarn build
          mv build ..
          mv build client
      - name: AWS CodeDeploy
        uses: sourcetoad/aws-codedeploy-action@v1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ap-northeast-1
          codedeploy_name: zignaly
          codedeploy_group: zignaly-nodejs-prod
          codedeploy_register_only: false
          s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          s3_folder: production
          max_polling_iterations: 60
          directory: ./
